-- Migration: Add address fields to users table
ALTER TABLE users ADD COLUMN phoneNumber VARCHAR(30) NULL;
ALTER TABLE users ADD COLUMN address VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN street VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN apartment VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN city VARCHAR(100) NULL;
ALTER TABLE users ADD COLUMN state VARCHAR(100) NULL;
